### ISSUE TITLE
List rabbitmq in Berksfile and metadata.rb

### ISSUE THREAD

**Issue by kgilpin** [conjurdemos/conjur-kitchen#1]
I think metadata.rb and Berksfile should list rabbitmq as a dependency.

**Comment by ghost** [comment]
Berksfile is looking to metadata.rb for the cookbook dependencies, so we don't need to list rabbitmq in the Berksfile as well.

https://github.com/conjurdemos/conjur-kitchen/blob/master/metadata.rb#L9
