### ISSUE TITLE
Show the steps used to create the system

### ISSUE THREAD

**Issue by kgilpin** [conjurdemos/conjur-kitchen#2]
It would be great to see the steps performed when creating the variables and otherwise setting up the system; including Conjur and any other config/install steps. Even ChefDK.

**Comment by ghost** [comment]
I added in steps to install the conjur CLI, ChefDK and the kitchen-docker gem. I also added the commands to create the variables. Setting up a conjur system getting out of scope I think. Pointing to the existing docs should be okay.
